### PR TITLE
Rework subprocess execution to check return code when using `.!` and fix tests

### LINKED ISSUE #207: Sandbox run fails to start but task result is [success]
In conductR 2 (macOS) it is required to create network aliases.

When the aliases are missing, the command to start the `sandbox` properly reports that the sandbox can't be started and it even lists the command to solve the issue. But the result of the sbt task is `[success]` (painted green) giving the appearance that the command succeeded:

```
> sandbox run 2.0.0 -n 3 --feature visualization
15:47:20.272 [pool-37-thread-4] DEBUG c.l.l.i.api.tools.ServiceDetector - Loading service discovery class: com.lightbend.lagom.internal.javadsl.server.JavadslServiceDiscovery
15:47:20.322 [pool-37-thread-2] DEBUG c.l.l.i.api.tools.ServiceDetector - Loading service discovery class: com.lightbend.lagom.internal.javadsl.server.JavadslServiceDiscovery
15:47:20.392 [pool-37-thread-1] DEBUG c.l.l.i.api.tools.ServiceDetector - Loading service discovery class: com.lightbend.lagom.internal.javadsl.server.JavadslServiceDiscovery
15:47:20.452 [pool-37-thread-3] DEBUG c.l.l.i.api.tools.ServiceDetector - Loading service discovery class: com.lightbend.lagom.internal.javadsl.server.JavadslServiceDiscovery
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Whoops. Network address aliases are required so that the sandbox can operate as a cluster of machines.

Please run the following and then try your command again:

sudo ifconfig lo0 alias 192.168.10.1 255.255.255.0
sudo ifconfig lo0 alias 192.168.10.2 255.255.255.0
sudo ifconfig lo0 alias 192.168.10.3 255.255.255.0

[success] Total time: 4 s, completed Feb 20, 2017 3:47:23 PM <--- see here
```

### PR DESCRIPTION
**Pull request by longshorej**
This will ensure SBT commands indicate an error has occurred if one has. Fixes #207.

I think this is reasonable behavior, as a user I would expect SBT commands to indicate an error has occurred if the commands are reliant on a subprocess exiting successfully.

Manual test:

```
[eslite]> sandbox run
The version of ConductR need to be set.
Please visit https://www.lightbend.com/product/conductr/developer to obtain the current version information.
[error] ({.}/*:sandboxRunTaskInternal) java.lang.IllegalArgumentException: requirement failed: sandbox exited with 1
[error] ({.}/*:sandbox) java.lang.IllegalArgumentException: requirement failed: sandbox exited with 1
[error] Total time: 2 s, completed Feb 21, 2017 10:33:25 AM
```

### CODE REVIEW

File: src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala [hunk 1]
```diff
@@ -372,13 +371,21 @@ object ConductrPlugin extends AutoPlugin {
...
 
   private def conductSubtask(command: String, args: Seq[String]): Unit =
-    Process(Seq("conduct", command) ++ args).!
+    runProcess(Seq("conduct", command) ++ args)
+
+  private def runProcess(args: Seq[String], message: String = ""): Unit = {
+    val code = Process(args).!
+
+    if (code != 0) {
+      throw new IllegalStateException(if (message == "") s"exited with $code" else message)
```
Comment (markusjura) [inline src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala]: Use `error` with a message instead of throwing an exception.

**Comment by longshorej** [comment]
Here's another test with the exact situation the issue was referring to:

```
[visualizer] $ sandbox run 2.0.0 -n 3 --feature visualization
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Whoops. Network address aliases are required so that the sandbox can operate as a cluster of machines.

Please run the following and then try your command again:

sudo ifconfig lo:0 192.168.10.1 netmask 255.255.255.0 up
sudo ifconfig lo:1 192.168.10.2 netmask 255.255.255.0 up
sudo ifconfig lo:2 192.168.10.3 netmask 255.255.255.0 up

[error] ({.}/*:sandboxRunTaskInternal) java.lang.IllegalStateException: exited with 1
[error] ({.}/*:sandbox) java.lang.IllegalStateException: exited with 1
[error] Total time: 1 s, completed Feb 21, 2017 10:34:53 AM
```

File: src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala (hunk 1 above)
Comment (longshorej) [inline src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala]: Thanks! That's set - here's output showing less noisiness as a result.

```
[visualizer] $ sandbox run
The version of ConductR need to be set.
Please visit https://www.lightbend.com/product/conductr/developer to obtain the current version information.
[error] ({.}/*:sandboxRunTaskInternal) exited with 1
[error] ({.}/*:sandbox) exited with 1
[error] Total time: 1 s, completed Feb 21, 2017 10:40:51 AM
```

**Comment by longshorej** [comment]
Okay, so this PR has actually revealed that some tests aren't working as intended -- before, these errors were hidden because SBT's commands didn't fail when a `sandbox` or `conduct` invocation fail, thus hiding the test failure. I'll try to fix these up and then comment on the justification for the various changes.

File: .travis.yml [hunk 2]
```diff
@@ -23,6 +23,8 @@ install:
   # Warm up some caches so that our tests don't timeout
   - sandbox run 2.0.0 -f visualization -f monitoring > /dev/null
   - conduct load -q cassandra
+  - conduct load -q cinnamon-grafana-docker:v2
```
Comment (longshorej) [inline .travis.yml]: A few more bundles had to be preloaded - we didn't notice before because errors were ignored.

File: src/main/scala/com/lightbend/conductr/sbt/ConductRImport.scala [hunk 3]
```diff
@@ -34,6 +34,10 @@ object ConductrImport {
   )
 
   object ConductrKeys {
+    val dryRun = SettingKey[Boolean](
```
Comment (longshorej) [inline src/main/scala/com/lightbend/conductr/sbt/ConductRImport.scala]: Two of the tests set this to `true` because they are only intended to test the argument parsing, not the task itself, so this mechanism basically disables the task execution and it just returns.

File: src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala [hunk 4]
```diff
@@ -312,39 +323,39 @@ object ConductrPlugin extends AutoPlugin {
         features.flatMap(Flags.feature +: _) ++
         ports.withFlag(Flags.port) ++
         logLevel.withFlag(Flags.logLevel) ++
-        conductrRoles.map(_.asConsoleNArg).withFlag(Flags.conductrRole) ++
+        conductrRoles.flatMap(r => if (r.nonEmpty) Flags.conductrRole +: r.toSeq else r) ++
```
Comment (longshorej) [inline src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala]: Roles weren't being passed properly to `conduct-cli` - they would be concatenated as a single string separated by ` ` instead of as separate arguments.

```
Before: Array("--conductr-role", "role1 role2")
After:  Array("--conductr-role", "role1", "role2")
```

File: src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala [hunk 5]
```diff
@@ -411,6 +430,12 @@ object ConductrPlugin extends AutoPlugin {
           .map { _ => SandboxHelp }
           .!!! { "Usage: sandbox --help" }
 
+      // This parser is triggering the help of the sandbox sub command if no argument for this command is specified
```
Comment (longshorej) [inline src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala]: `sandbox` now invokes `sandbox -h` -- much like `conduct`

File: src/sbt-test/sbt-conductr/conduct-common-args/test [hunk 6]
```diff
@@ -1,3 +1,5 @@
+> set ConductrKeys.dryRun in Global := true
```
Comment (longshorej) [inline src/sbt-test/sbt-conductr/conduct-common-args/test]: This test is only here to test argument parsing, so we enable `dryRun`

File: src/sbt-test/sbt-conductr/sandbox-all-args/test [hunk 7]
```diff
@@ -1,3 +1,5 @@
+> set ConductrKeys.dryRun in Global := true
```
Comment (longshorej) [inline src/sbt-test/sbt-conductr/sandbox-all-args/test]: This test is only here to test argument parsing, so we enable `dryRun`

File: src/sbt-test/sbt-conductr/sandbox-conductr-roles/test [hunk 8]
```diff
@@ -4,7 +4,7 @@
 
 > sandbox stop
 
-> sandbox run 2.0.0 --nr-of-containers 4 --conductr-role new-role --conductr-role other-role
+> sandbox run 2.0.0 --nr-of-containers 4 --conductr-role new-role haproxy --conductr-role other-role haproxy
```
Comment (longshorej) [inline src/sbt-test/sbt-conductr/sandbox-conductr-roles/test]: sandbox wouldn't ever start up because haproxy wouldn't get a resource offer due to missing role
